const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { WorkdaySync } = require('../sync-engine.js');
const sample = title => ({ version: 1, tasks: [{ id: 'a', title }], settings: {}, references: null });
function harness(local, row, metadata) {
  let data = local, remote = row, conflict = false, saved, writes = 0;
  const store = { get: async () => structuredClone(remote), put: async (payload, revision) => { writes++; if ((remote?.revision || 0) !== revision) return null; remote = { revision: revision + 1, payload: structuredClone(payload) }; return { revision: remote.revision }; } };
  const engine = new WorkdaySync({ store, read: () => structuredClone(data), apply: value => { data = structuredClone(value); }, metadata, persist: m => { saved = structuredClone(m); }, status: () => {}, conflict: v => { conflict = v; } });
  return { engine, store, edit: v => { data = v; engine.changed(); }, remote: v => { remote = v; }, get: () => ({ data, remote, conflict, saved, writes }) };
}
test('new device reads existing cloud agenda', async () => { const h = harness(sample('seed'), { revision: 3, payload: sample('cloud') }); await h.engine.initialize(false); assert.equal(h.get().data.tasks[0].title, 'cloud'); assert.equal(h.get().saved.revision, 3); });
test('new account initializes cloud', async () => { const h = harness(sample('seed'), null); await h.engine.initialize(false); await h.engine.sync(); assert.equal(h.get().remote.revision, 1); });
test('edit is persisted as pending before network', async () => { const h = harness(sample('same'), { revision: 1, payload: sample('same') }); await h.engine.initialize(true); h.edit(sample('new')); assert.equal(h.get().saved.pending, true); await h.engine.sync(); assert.equal(h.get().remote.payload.tasks[0].title, 'new'); assert.equal(h.get().saved.pending, false); });
test('stale offline edit cannot overwrite newer cloud', async () => { const h = harness(sample('local'), { revision: 2, payload: sample('remote') }, { revision: 1, pending: true }); await h.engine.initialize(true); await h.engine.sync(); assert.equal(h.get().conflict, true); assert.equal(h.get().writes, 0); });
test('concurrent write is rejected; explicit local choice uses latest revision', async () => { const h = harness(sample('same'), { revision: 1, payload: sample('same') }); await h.engine.initialize(true); h.edit(sample('local')); h.remote({ revision: 2, payload: sample('remote') }); await h.engine.sync(); assert.equal(h.get().remote.revision, 2); assert.equal(h.get().conflict, true); await h.engine.resolve(true); assert.equal(h.get().remote.revision, 3); assert.equal(h.get().remote.payload.tasks[0].title, 'local'); });
test('explicit cloud choice replaces local without writing', async () => { const h = harness(sample('local'), { revision: 2, payload: sample('remote') }, { revision: 1, pending: true }); await h.engine.initialize(true); await h.engine.resolve(false); assert.equal(h.get().data.tasks[0].title, 'remote'); assert.equal(h.get().writes, 0); });
test('edit during upload remains pending for next revision', async () => { const h = harness(sample('same'), { revision: 1, payload: sample('same') }); await h.engine.initialize(true); h.edit(sample('first')); let release; h.store.put = async () => new Promise(resolve => { release = resolve; }); const pending = h.engine.sync(); h.edit(sample('second')); release({ revision: 2 }); await pending; assert.equal(h.get().saved.pending, true); assert.equal(h.get().data.tasks[0].title, 'second'); });
test('edit during pull is never overwritten', async () => { const h = harness(sample('same'), { revision: 1, payload: sample('same') }); await h.engine.initialize(true); let release; h.store.get = () => new Promise(resolve => { release = resolve; }); const pending = h.engine.sync(); h.edit(sample('local')); release({ revision: 2, payload: sample('remote') }); await pending; assert.equal(h.get().data.tasks[0].title, 'local'); assert.equal(h.get().conflict, true); });
test('network failure retains local pending edits', async () => { const h = harness(sample('same'), { revision: 1, payload: sample('same') }); await h.engine.initialize(true); h.edit(sample('offline')); h.store.put = async () => { throw new Error('offline'); }; await h.engine.sync(); assert.equal(h.get().saved.pending, true); assert.equal(h.get().data.tasks[0].title, 'offline'); });
test('closed session cannot apply late network response', async () => { const h = harness(sample('same'), null); let release; h.store.get = () => new Promise(resolve => { release = resolve; }); const pending = h.engine.initialize(false); h.engine.close(); release({ revision: 8, payload: sample('other-account') }); await pending; assert.equal(h.get().data.tasks[0].title, 'same'); });
const context = { URL, crypto: require('node:crypto').webcrypto }; vm.createContext(context); vm.runInContext(fs.readFileSync(path.join(__dirname, '../app.js'), 'utf8'), context);
const model = context.WorkdayModel;
test('private references survive backup normalization; links are sanitized', () => { const raw = { version: 1, tasks: [{ id: 'a', title: 'Personal task' }], references: { catalog: { projects: [{ id: 'project-a', name: 'My project', chatUrl: 'javascript:alert(1)' }], chats: [] }, sheet: { rows: [{ key: 'row-1', title: 'Task', status: 'Waiting', tab: 'Sheet1' }] } } }; const result = model.normalizeState(raw); assert.equal(result.references.catalog.projects.length, 1); assert.equal(result.references.catalog.projects[0].chatUrl, ''); assert.equal(result.references.sheet.rows[0].key, 'row-1'); });
test('unsafe IDs cannot be inserted in HTML attributes', () => { assert.throws(() => model.normalizeReferences({ catalog: { projects: [{ id: '\" onclick=\"bad' }], chats: [] }, sheet: { rows: [] } })); });
test('old task-only backup remains supported', () => { const result = model.normalizeState({ version: 1, tasks: [{ title: 'Old task' }] }); assert.equal(result.references, null); assert.equal(result.tasks.length, 1); });
